----------------------------------------------------------------
Wed Oct 11 12:50:13 CEST 2023:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.16.1.1 - (1901046): instance a816c00e-018b-1e5b-c338-000001a1c1b0 
on database directory C:\Users\Victo\git\Biblioteca\database with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/Victo/.m2/repository/org/apache/derby/derby/10.16.1.1/derby-10.16.1.1.jar
java.vendor=Oracle Corporation
java.runtime.version=17.0.3+8-LTS-111
user.dir=C:\Users\Victo\git\Biblioteca
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 11 12:50:13 CEST 2023:
Shutting down instance a816c00e-018b-1e5b-c338-000001a1c1b0 on database directory C:\Users\Victo\git\Biblioteca\database with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93 
Wed Oct 11 12:50:13 CEST 2023 Thread[Thread-3,5,main] Cleanup action starting
ERROR XBM01: Startup failed due to an exception. See next exception for details. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.iapi.services.monitor.Monitor.exceptionStartingModule(Monitor.java:743)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1844)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 11 12:50:13 CEST 2023 Thread[Thread-3,5,main] Cleanup action starting
java.sql.SQLException: Failed to create database 'database', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:252)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2656)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ERROR XJ041: Failed to create database 'database', see the next exception for details.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 11 more
Caused by: ERROR XBM01: Startup failed due to an exception. See next exception for details. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.iapi.services.monitor.Monitor.exceptionStartingModule(Monitor.java:743)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1844)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	... 8 more
Caused by: ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	... 13 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Startup failed due to an exception. See next exception for details. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:252)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:438)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2657)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ERROR XBM01: Startup failed due to an exception. See next exception for details. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 14 more
Caused by: ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	... 8 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.sql.SQLInvalidAuthorizationSpecException: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:439)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2657)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	... 8 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
ERROR 28502: The user name 'derbyuser ' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:771)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:527)
	at org.apache.derby.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:460)
	at org.apache.derby.impl.db.BasicDatabase.bootServiceModule(BasicDatabase.java:945)
	at org.apache.derby.impl.db.BasicDatabase.boot(BasicDatabase.java:201)
	at org.apache.derby.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1989)
	at org.apache.derby.impl.services.monitor.TopService.bootModule(TopService.java:334)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1817)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1011)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:45)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4004)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2649)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:430)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:630)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:400)
	at org.apache.derby.iapi.jdbc.InternalDriver$LoginCallable.call(InternalDriver.java:376)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
============= end nested exception, level (3) ===========
Cleanup action completed
